// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupportDesk.Infrastructure.Persistence;

#nullable disable

namespace SupportDesk.Infrastructure.Migrations
{
    [DbContext(typeof(SupportDbContext))]
    [Migration("20260926183612_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupportDesk.Domain.Entities.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxOpenTickets")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Agents_Email");

                    b.ToTable("Agents", null, t =>
                        {
                            t.HasCheckConstraint("CK_Agents_MaxOpenTickets", "[MaxOpenTickets] > 0");
                        });
                });

            modelBuilder.Entity("SupportDesk.Domain.Entities.AgentSpecialization", b =>
                {
                    b.Property<int>("AgentId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("AgentId", "CategoryId");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_AgentSpecializations_CategoryId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("CategoryId"), new[] { "AgentId" });

                    b.ToTable("AgentSpecializations", (string)null);
                });

            modelBuilder.Entity("SupportDesk.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ForcesCriticalPriority")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequiresSpecialist")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Categories_Name");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("SupportDesk.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Customers_Email");

                    b.ToTable("Customers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Customers_Tier", "[Tier] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("SupportDesk.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedAgentId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("DueAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAgentId")
                        .HasDatabaseName("IX_Tickets_AssignedAgentId")
                        .HasFilter("[AssignedAgentId] IS NOT NULL");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Tickets_CategoryId");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_Tickets_CustomerId");

                    b.HasIndex("DueAtUtc")
                        .HasDatabaseName("IX_Tickets_DueAtUtc");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("UQ_Tickets_Reference");

                    b.HasIndex("Status", "Priority")
                        .HasDatabaseName("IX_Tickets_Status_Priority");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Status", "Priority"), new[] { "DueAtUtc", "AssignedAgentId" });

                    b.ToTable("Tickets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tickets_Priority", "[Priority] BETWEEN 1 AND 4");

                            t.HasCheckConstraint("CK_Tickets_Status", "[Status] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("SupportDesk.Domain.Entities.AgentSpecialization", b =>
                {
                    b.HasOne("SupportDesk.Domain.Entities.Agent", "Agent")
                        .WithMany("Specializations")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupportDesk.Domain.Entities.Category", "Category")
                        .WithMany("Specialists")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SupportDesk.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("SupportDesk.Domain.Entities.Agent", "AssignedAgent")
                        .WithMany("Tickets")
                        .HasForeignKey("AssignedAgentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SupportDesk.Domain.Entities.Category", "Category")
                        .WithMany("Tickets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupportDesk.Domain.Entities.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedAgent");

                    b.Navigation("Category");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SupportDesk.Domain.Entities.Agent", b =>
                {
                    b.Navigation("Specializations");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("SupportDesk.Domain.Entities.Category", b =>
                {
                    b.Navigation("Specialists");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("SupportDesk.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
